name: Go-Build

on:
  push:
    branches:
      - "main"
    paths:
      - .github/workflows/**
      - cmd/**
      - internal/**
      - go.mod
  pull_request:
    branches:
      - "main"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Get Build Time
        run: echo "build_data=$(date +%Y%m%d)" >> "$GITHUB_ENV"

      - name: Build
        run: go build -o fsd-server-linux-amd64-$build_data-${{ github.sha }} ./cmd/fsd-server/

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          install-only: true

      - name: Compress executable file
        run: upx -fq -9 ./fsd-server-linux-amd64-$build_data-${{ github.sha }}

      - uses: actions/upload-artifact@v4
        with:
          name: linux-nightly
          path: ./fsd-server-linux-amd64-$build_data-${{ github.sha }}

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Get Build Time
        run: echo "build_data=$(date +%Y%m%d)" >> "$GITHUB_ENV"

      - name: Build
        run: go build -o fsd-server-windows-amd64-$build_data-${{ github.sha }}.exe ./cmd/fsd-server/

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          install-only: true

      - name: Compress executable file
        run: upx -fq -9 ./fsd-server-windows-amd64-$build_data-${{ github.sha }}.exe

      - uses: actions/upload-artifact@v4
        with:
          name: windows-nightly
          path: ./fsd-server-windows-amd64-$build_data-${{ github.sha }}.exe