name: Go-Build

on:
  push:
    branches:
      - "main"
    paths:
      - cmd/**
      - internal/**
      - go.mod
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Build Linux
        run: go build -o fsd-server-linux-nightly -v ./cmd/fsd-server/

      - name: Build Windows
        run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o fsd-server-windows-amd64-nightly.exe ./cmd/fsd-server/

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          install-only: true

      - name: Compress executable file
        run: |
          upx -fq -9 ./fsd-server-linux-nightly
          upx -fq -9 ./fsd-server-windows-amd64-nightly.exe

      - uses: actions/upload-artifact@v4
        with:
          name: linux-nightly
          path: ./fsd-server-linux-nightly

      - uses: actions/upload-artifact@v4
        with:
          name: windows-nightly
          path: ./fsd-server-windows-amd64-nightly.exe
